version: "2"
services:
  rdb:
    build: ./postgres
    environment:
      POSTGRES_USER: sample_root
      POSTGRES_PASSWORD: sample_pass

  session_db:
    image: redis:latest

  kong-database:
    image: postgres:latest
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong

  api1:
    build: ./api1
    links:
      - rdb
      - session_db
    volumes:
      - ./api1:/usr/src/app
    environment:
      RACK_ENV: development
      DB_USER: api1_user
      DB_PASS: api1_pass
      DB_NAME: api1_db
    working_dir: /usr/src/app
    depends_on:
      - rdb
      - session_db

  kong:
    image: mashape/kong
    links:
      - api1
      - kong-database
    environment:
      KONG_LOG_LEVEL: info
      KONG_PG_HOST: kong-database
    ports:
      - 3000:3000
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    security_opt:
      - label:seccomp:unconfined
    depends_on:
      - api1
      - kong-database
 
  top:
    build: ./top
    ports:
      - 80:3000
    links:
      - api1
      - kong
      - session_db
    volumes:
      - ./top:/usr/src/app
    environment:
      RACK_ENV: development
    working_dir: /usr/src/app
    depends_on:
      - api1
      - kong
      - session_db
